import { OPENAI_API_KEY } from '@/lib/env';
import { InputData } from '@/components/inputs/InputPanel';
import { generateChart } from '../api';

/**
 * Types of agents available in the system
 */
export type AgentType = 'main' | 'quarterly' | 'analytics';

/**
 * Agent configuration
 */
interface AgentConfig {
  name: string;
  description: string;
  capabilities: string[];
}

/**
 * Available agents and their configurations
 */
const AGENTS: Record<AgentType, AgentConfig> = {
  main: {
    name: 'Main Report Agent',
    description: 'Generates comprehensive reports based on input data',
    capabilities: ['Text generation', 'Data analysis', 'Chart recommendations']
  },
  quarterly: {
    name: 'Quarterly Report Agent',
    description: 'Specializes in quarterly financial and performance reports',
    capabilities: ['Financial analysis', 'Trend identification', 'Executive summaries']
  },
  analytics: {
    name: 'Analytics Report Agent',
    description: 'Focuses on data-driven insights and visualizations',
    capabilities: ['Advanced data analysis', 'Statistical modeling', 'Visualization generation']
  }
};

/**
 * Input data for running an agent
 */
export interface AgentInput {
  reportType: string;
  reportDescription?: string;
  selectedModel: string;
  policyDocuments?: File[];
  dataFiles?: File[];
  performanceLevel?: number;
  factualConfidence?: boolean;
  draftMode?: boolean;
  sourceCitations?: boolean;
}

/**
 * Determine which agent to use based on input data
 */
export function determineAgent(input: AgentInput): AgentType {
  if (input.reportType.toLowerCase().includes('quarterly')) {
    return 'quarterly';
  } else if (input.reportType.toLowerCase().includes('analytics')) {
    return 'analytics';
  }
  return 'main';
}

/**
 * Run an agent with the provided input data
 */
export async function runAgent(input: AgentInput): Promise<string> {
  const agentType = determineAgent(input);
  const agent = AGENTS[agentType];
  
  console.log(`Running ${agent.name} for ${input.reportType} report`);
  
  // This is a simulation of running the agent with the OpenAI API
  // In a real implementation, this would make an API call to OpenAI
  
  // Simulate processing time
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  // Generate a sample report based on the input
  const report = generateSampleReport(input, agentType);
  
  return report;
}

/**
 * Generate a sample report (for demonstration purposes)
 */
async function generateSampleReport(input: AgentInput, agentType: AgentType): Promise<string> {
  // Generate a chart for the report
  let chartPlaceholder = '';
  
  try {
    if (agentType === 'analytics' || agentType === 'quarterly') {
      // For analytics and quarterly reports, include a chart
      const chartData = generateSampleChartData(input.reportType);
      
      // This would be replaced with actual chart generation in production
      chartPlaceholder = `
[CHART: This is a placeholder for a ${chartData.chartType} chart showing ${chartData.title}. 
In the actual implementation, this would be replaced with a visualization generated by the visualization agent.]
`;
    }
  } catch (error) {
    console.error('Error generating chart:', error);
    chartPlaceholder = '[CHART: Unable to generate chart]';
  }
  
  // Ensure anti-hallucination features are properly set with defaults
  const enhancedInput = {
    ...input,
    factualConfidence: input.factualConfidence !== undefined ? input.factualConfidence : true,
    draftMode: input.draftMode !== undefined ? input.draftMode : true,
    sourceCitations: input.sourceCitations !== undefined ? input.sourceCitations : true
  };
  
  // Generate report content based on agent type
  let content = '';
  
  switch (agentType) {
    case 'quarterly':
      content = generateQuarterlyReport(enhancedInput, chartPlaceholder);
      break;
    case 'analytics':
      content = generateAnalyticsReport(enhancedInput, chartPlaceholder);
      break;
    default:
      content = generateMainReport(enhancedInput, chartPlaceholder);
  }
  
  return content;
}

/**
 * Generate sample chart data based on report type
 */
function generateSampleChartData(reportType: string): { chartType: string; title: string; data: any } {
  if (reportType.toLowerCase().includes('quarterly')) {
    return {
      chartType: 'bar',
      title: 'Quarterly Performance',
      data: {
        categories: ['Q1', 'Q2', 'Q3', 'Q4'],
        values: [120, 150, 180, 210]
      }
    };
  } else if (reportType.toLowerCase().includes('analytics')) {
    return {
      chartType: 'pie',
      title: 'Revenue Distribution',
      data: {
        labels: ['Product A', 'Product B', 'Product C', 'Product D'],
        values: [30, 25, 15, 30]
      }
    };
  } else {
    return {
      chartType: 'line',
      title: 'Annual Trend',
      data: {
        x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        y: [50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160]
      }
    };
  }
}

/**
 * Generate a quarterly report
 */
function generateQuarterlyReport(input: AgentInput, chartPlaceholder: string): string {
  const userDescription = input.reportDescription 
    ? `\n\n## User Requirements\n${input.reportDescription}\n` 
    : '';
    
  // Add anti-hallucination features
  const factualConfidenceHeader = input.factualConfidence 
    ? `\n\n## Confidence Levels\nThis report uses the following confidence indicators:\n- **[High Confidence]**: Directly supported by provided data\n- **[Medium Confidence]**: Inferred from provided data with reasonable certainty\n- **[Low Confidence]**: Speculative based on limited data\n- **[No Data]**: No supporting data available\n`
    : '';
    
  const draftModeHeader = input.draftMode
    ? `\n\n## Draft Status\nThis is a DRAFT report generated based on limited data. All conclusions should be verified against primary sources before making decisions.\n`
    : '';
    
  const sourceCitationsNote = input.sourceCitations
    ? `\n\nSource citations are provided in [brackets] throughout this report, referencing the uploaded documents that support each claim.`
    : '';
    
  // Add confidence levels to statements if factualConfidence is enabled
  const confidencePrefixes = input.factualConfidence
    ? {
        high: '[High Confidence] ',
        medium: '[Medium Confidence] ',
        low: '[Low Confidence] ',
        none: '[No Data] '
      }
    : {
        high: '',
        medium: '',
        low: '',
        none: ''
      };
      
  // Add source citations if enabled
  const sourceCitations = input.sourceCitations
    ? {
        revenue: ' [Source: Financial Data Q4]',
        expenses: ' [Source: Financial Data Q4]',
        margin: ' [Source: Financial Data Q4]',
        growth: ' [Source: Financial Data Q1-Q4]',
        measures: ' [Source: Policy Document - Cost Reduction]',
        products: ' [Source: Sales Report]'
      }
    : {
        revenue: '',
        expenses: '',
        margin: '',
        growth: '',
        measures: '',
        products: ''
      };
      
  // Add tentative language if draft mode is enabled
  const draftLanguage = input.draftMode
    ? {
        prefix: 'Based on the available data, ',
        tentative: ' appears to',
        may: ' may',
        suggests: ' suggests that',
        potentially: ' potentially'
      }
    : {
        prefix: '',
        tentative: '',
        may: '',
        suggests: '',
        potentially: ''
      };

  return `# Quarterly Financial Report
## ${input.reportType}
### Generated with ${input.selectedModel}${userDescription}${factualConfidenceHeader}${draftModeHeader}${sourceCitationsNote}

## Executive Summary
${draftLanguage.prefix}This quarterly report provides an overview of the company's financial performance for the most recent quarter. The analysis is based on the provided financial data and policy documents.

## Financial Highlights
- ${confidencePrefixes.high}Revenue increased by 15% compared to the previous quarter${sourceCitations.revenue}
- ${confidencePrefixes.high}Operating expenses decreased by 5%${sourceCitations.expenses}
- ${confidencePrefixes.medium}Net profit margin${draftLanguage.tentative} improved to 22%${sourceCitations.margin}

${chartPlaceholder}

## Key Observations
1. ${confidencePrefixes.medium}The company${draftLanguage.tentative} has shown consistent growth over the past four quarters${sourceCitations.growth}
2. ${confidencePrefixes.high}Cost-cutting measures implemented last quarter have shown positive results${sourceCitations.measures}
3. ${confidencePrefixes.low}New product lines${draftLanguage.may} have contributed significantly to revenue growth${sourceCitations.products}

## Recommendations
- ${confidencePrefixes.low}Continue investing in high-performing product lines
- ${confidencePrefixes.low}Explore opportunities for market expansion
- ${confidencePrefixes.medium}Maintain cost discipline while supporting growth initiatives

${input.draftMode ? '**DRAFT REPORT:** This document is a preliminary analysis based on limited data and should be reviewed thoroughly before making decisions.' : '*This report was generated automatically and should be reviewed by financial experts before distribution.*'}
`;
}

/**
 * Generate an analytics report
 */
function generateAnalyticsReport(input: AgentInput, chartPlaceholder: string): string {
  const userDescription = input.reportDescription 
    ? `\n\n## User Requirements\n${input.reportDescription}\n` 
    : '';
    
  // Add anti-hallucination features
  const factualConfidenceHeader = input.factualConfidence 
    ? `\n\n## Confidence Levels\nThis report uses the following confidence indicators:\n- **[High Confidence]**: Directly supported by provided data\n- **[Medium Confidence]**: Inferred from provided data with reasonable certainty\n- **[Low Confidence]**: Speculative based on limited data\n- **[No Data]**: No supporting data available\n`
    : '';
    
  const draftModeHeader = input.draftMode
    ? `\n\n## Draft Status\nThis is a DRAFT report generated based on limited data. All conclusions should be verified against primary sources before making decisions.\n`
    : '';
    
  const sourceCitationsNote = input.sourceCitations
    ? `\n\nSource citations are provided in [brackets] throughout this report, referencing the uploaded documents that support each claim.`
    : '';
    
  // Add confidence levels to statements if factualConfidence is enabled
  const confidencePrefixes = input.factualConfidence
    ? {
        high: '[High Confidence] ',
        medium: '[Medium Confidence] ',
        low: '[Low Confidence] ',
        none: '[No Data] '
      }
    : {
        high: '',
        medium: '',
        low: '',
        none: ''
      };
      
  // Add source citations if enabled
  const sourceCitations = input.sourceCitations
    ? {
        cac: ' [Source: Customer Acquisition Data]',
        clv: ' [Source: Customer Lifetime Value Analysis]',
        conversion: ' [Source: Conversion Metrics Q4]',
        retention: ' [Source: Customer Retention Report]',
        segments: ' [Source: Customer Segmentation Analysis]',
        revenue: ' [Source: Revenue Distribution Report]'
      }
    : {
        cac: '',
        clv: '',
        conversion: '',
        retention: '',
        segments: '',
        revenue: ''
      };
      
  // Add tentative language if draft mode is enabled
  const draftLanguage = input.draftMode
    ? {
        prefix: 'Based on the available data, ',
        tentative: ' appears to',
        may: ' may',
        suggests: ' suggests that',
        potentially: ' potentially',
        estimated: ' estimated at'
      }
    : {
        prefix: '',
        tentative: '',
        may: '',
        suggests: '',
        potentially: '',
        estimated: ''
      };

  return `# Data Analytics Report
## ${input.reportType}
### Generated with ${input.selectedModel}${userDescription}${factualConfidenceHeader}${draftModeHeader}${sourceCitationsNote}

## Overview
${draftLanguage.prefix}This report presents an analysis of the provided data, identifying key trends, patterns, and insights that${draftLanguage.may} inform business decisions.

## Key Metrics
- ${confidencePrefixes.medium}Customer acquisition cost${draftLanguage.estimated} $42.15${sourceCitations.cac}
- ${confidencePrefixes.medium}Customer lifetime value${draftLanguage.estimated} $156.78${sourceCitations.clv}
- ${confidencePrefixes.high}Conversion rate: 3.2%${sourceCitations.conversion}
- ${confidencePrefixes.high}Retention rate: 68%${sourceCitations.retention}

${chartPlaceholder}

## Segment Analysis
${draftLanguage.prefix}The data${draftLanguage.suggests} distinct customer segments with different behaviors${sourceCitations.segments}:
1. ${confidencePrefixes.medium}High-value customers${draftLanguage.tentative} represent 15% of base${draftLanguage.tentative} generating 40% of revenue${sourceCitations.revenue}
2. ${confidencePrefixes.medium}Mid-tier customers${draftLanguage.tentative} represent 45% of base${draftLanguage.tentative} generating 50% of revenue${sourceCitations.revenue}
3. ${confidencePrefixes.medium}Low-value customers${draftLanguage.tentative} represent 40% of base${draftLanguage.tentative} generating 10% of revenue${sourceCitations.revenue}

## Recommendations
- ${confidencePrefixes.low}Implement targeted marketing campaigns for high-value customer segments
- ${confidencePrefixes.low}Develop retention strategies for mid-tier customers
- ${confidencePrefixes.low}Evaluate acquisition channels for low-value customers

${input.draftMode ? '**DRAFT REPORT:** This document is a preliminary analysis based on limited data and should be reviewed thoroughly before making decisions.' : '*This report was generated using advanced analytics algorithms and should be used as a starting point for further investigation.*'}
`;
}

/**
 * Generate a main report
 */
function generateMainReport(input: AgentInput, chartPlaceholder: string): string {
  const userDescription = input.reportDescription 
    ? `\n\n## User Requirements\n${input.reportDescription}\n` 
    : '';
    
  // Add confidence level indicators if factual confidence is enabled
  const factualConfidenceHeader = input.factualConfidence
    ? `\n\n## Confidence Levels
- **[High Confidence]**: Directly supported by provided data
- **[Medium Confidence]**: Inferred from provided data
- **[Low Confidence]**: Based on general knowledge, limited data support
- **[No Data]**: No supporting data available`
    : '';

  // Add draft mode header if enabled
  const draftModeHeader = input.draftMode
    ? `\n\n## Draft Status
**DRAFT REPORT:** This document is in draft mode. Conclusions should be verified against primary sources before making decisions.`
    : '';

  // Add source citations note if enabled
  const sourceCitationsNote = input.sourceCitations
    ? `\n\n## Source Citations
The following report references uploaded documents as sources for claims where available.`
    : '';

  // Add confidence prefixes if factual confidence is enabled
  const confidencePrefixes = input.factualConfidence
    ? {
        high: '[High Confidence] ',
        medium: '[Medium Confidence] ',
        low: '[Low Confidence] ',
        noData: '[No Data] '
      }
    : {
        high: '',
        medium: '',
        low: '',
        noData: ''
      };

  // Add source citations if enabled
  const sourceCitations = input.sourceCitations
    ? {
        revenue: ' [Source: Revenue Reports]',
        satisfaction: ' [Source: Customer Satisfaction Survey]',
        engagement: ' [Source: Employee Engagement Survey]',
        brand: ' [Source: Brand Recognition Analysis]',
        portfolio: ' [Source: Product Portfolio Review]',
        international: ' [Source: Market Presence Analysis]',
        it: ' [Source: IT Systems Audit]',
        turnover: ' [Source: HR Turnover Report]'
      }
    : {
        revenue: '',
        satisfaction: '',
        engagement: '',
        brand: '',
        portfolio: '',
        international: '',
        it: '',
        turnover: ''
      };
      
  // Add tentative language if draft mode is enabled
  const draftLanguage = input.draftMode
    ? {
        prefix: 'Based on the available data, ',
        tentative: ' appears to',
        may: ' may',
        suggests: ' suggests that',
        potentially: ' potentially',
        estimated: ' estimated at'
      }
    : {
        prefix: '',
        tentative: '',
        may: '',
        suggests: '',
        potentially: '',
        estimated: ''
      };

  return `# Comprehensive Business Report
## ${input.reportType}
### Generated with ${input.selectedModel}${userDescription}${factualConfidenceHeader}${draftModeHeader}${sourceCitationsNote}

## Introduction
${draftLanguage.prefix}This report provides a comprehensive analysis of the company's current state, based on the provided data and policy documents. It covers key aspects of the business including operations, finances, and strategic direction.

## Performance Overview
${draftLanguage.prefix}The company has${draftLanguage.tentative} demonstrated solid performance across key metrics:
- ${confidencePrefixes.medium}Revenue growth${draftLanguage.estimated} 12% year-over-year${sourceCitations.revenue}
- ${confidencePrefixes.medium}Customer satisfaction${draftLanguage.estimated} 4.2/5.0${sourceCitations.satisfaction}
- ${confidencePrefixes.medium}Employee engagement${draftLanguage.estimated} 3.8/5.0${sourceCitations.engagement}

${chartPlaceholder}

## SWOT Analysis
### Strengths
- ${confidencePrefixes.medium}Strong brand recognition${sourceCitations.brand}
- ${confidencePrefixes.medium}Diverse product portfolio${sourceCitations.portfolio}
- ${confidencePrefixes.low}Experienced leadership team

### Weaknesses
- ${confidencePrefixes.medium}Limited international presence${sourceCitations.international}
- ${confidencePrefixes.medium}Legacy IT systems${sourceCitations.it}
- ${confidencePrefixes.medium}High employee turnover in certain departments${sourceCitations.turnover}

### Opportunities
- ${confidencePrefixes.low}Emerging markets expansion
- ${confidencePrefixes.low}Digital transformation
- ${confidencePrefixes.low}Strategic partnerships

### Threats
- ${confidencePrefixes.low}Increasing competition
- ${confidencePrefixes.low}Regulatory changes
- ${confidencePrefixes.low}Economic uncertainty

## Strategic Recommendations
1. ${confidencePrefixes.low}Accelerate digital transformation initiatives
2. ${confidencePrefixes.low}Explore strategic partnerships for international expansion
3. ${confidencePrefixes.low}Invest in employee development and retention programs
4. ${confidencePrefixes.low}Optimize product portfolio based on performance data

${input.draftMode ? '**DRAFT REPORT:** This document is a preliminary analysis based on limited data and should be reviewed thoroughly before making decisions.' : '*This report was generated automatically based on the provided inputs and should be reviewed by management before implementation of any recommendations.*'}
`;
} 