'use client';

import React, { useState, useEffect } from 'react';
import { generateChart } from '@/lib/api';
import { Spinner } from './ui/spinner';

interface ChartDisplayProps {
  chartType: string;
  data: any;
  title?: string;
  xLabel?: string;
  yLabel?: string;
  colors?: string[];
  width?: string;
  height?: string;
  className?: string;
}

/**
 * Component for displaying charts generated by the Python visualization agent
 */
export default function ChartDisplay({
  chartType,
  data,
  title,
  xLabel,
  yLabel,
  colors,
  width = '100%',
  height = 'auto',
  className = '',
}: ChartDisplayProps) {
  const [chartImage, setChartImage] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadChart = async () => {
      try {
        setLoading(true);
        setError(null);
        
        const result = await generateChart(
          chartType,
          data,
          title,
          xLabel,
          yLabel,
          colors
        );
        
        setChartImage(result.image);
      } catch (err) {
        console.error('Error loading chart:', err);
        setError('Failed to load chart. Please try again later.');
      } finally {
        setLoading(false);
      }
    };

    loadChart();
  }, [chartType, data, title, xLabel, yLabel, colors]);

  if (loading) {
    return (
      <div className={`flex justify-center items-center ${className}`} style={{ width, height: height === 'auto' ? '300px' : height }}>
        <Spinner size="lg" />
      </div>
    );
  }

  if (error) {
    return (
      <div className={`flex justify-center items-center text-red-500 ${className}`} style={{ width, height }}>
        <p>{error}</p>
      </div>
    );
  }

  if (!chartImage) {
    return (
      <div className={`flex justify-center items-center text-gray-500 ${className}`} style={{ width, height }}>
        <p>No chart data available</p>
      </div>
    );
  }

  return (
    <div className={className} style={{ width, height }}>
      <img 
        src={`data:image/png;base64,${chartImage}`} 
        alt={title || 'Chart'} 
        style={{ width: '100%', height: '100%', objectFit: 'contain' }} 
      />
    </div>
  );
} 